### ISSUE TITLE
Example using camera or gallery

### ISSUE THREAD

**Issue by mlopez0** [dvagala/pytorch-flutter-FFI-example#1]
Hi, I'm coming from [this package](https://github.com/AneeqMalik/flutter_pytorch/issues/2) where you state an improved version using FFI, I downloaded your version but I'm not sure how to use it! 

Is it possible to upload an example as [this](https://github.com/AneeqMalik/flutter_pytorch/tree/main/example) using the camera or the gallery?

**Comment by dvagala** [comment]
Hey! This is not a ready-to-use flutter package. This is just a bare minimum example of how to do model inference, to provide inspiration for package creators. Currently, I don't have time to modify this repo, sorryy
