### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by cyrillkuettel** [dvagala/pytorch-flutter-FFI-example#2]
First of all, many thanks for provding this repo. I have seen the benchmarks and I would like to reproduce them. 
Where did  you get the models with different input shape? Is it a different model for each input shape?

I think you used [LDC](https://github.com/xavysp/LDC), but I'm not sure of I can find out what input shape it supports.

```
Input shape (1, 3, 350, 350) - inference 250ms
Input shape (1, 3, 700, 700) -  inference 314ms
Input shape (1, 3, 2000, 2000) -  inference 580ms
Input shape (1, 3, 8750, 8750) -  inference 12114ms
```

Where can I find models that support (1, 3, 700, 700)  input shape and higher?

**Comment by dvagala** [comment]
Hey, I believe the LDC supports `( 1, 3, x, x)` where `x` is the dimension of an image. That specific neural network is based on convolution layers. So it doesn't have a fixed input shape, but it can take any image and go through all the pixels with convolution kernel and process the image. But please note I'm no neural net expert, so take it with a grain of salt 😄

**Comment by cyrillkuettel** [comment]
Alright thank you that makes sense if it has dynamic inputs.
